[project]
name = "ud-langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.9.0",
    "isort>=7.0.0",
    "jsonpatch>=1.33",
    "langchain>=0.3.27",
    "langchain-core>=0.3.79",
    "langchain-google-vertexai>=2.1.2",
    "langchain-groq>=0.3.8",
    "langchain-ollama>=0.3.10",
    "langchain-openai>=0.3.35",
    "python-dotenv>=1.1.1",
]
